Update: create_workshop
inserts agregados

TODO:
-verificar tildes en PROCESSES y en general
-hacer pruebas: ERROR EN CUSTOM SERVICE:
org.springframework.dao.InvalidDataAccessResourceUsageException: Error calling CallableStatement.getMoreResults [ERROR: no existe la relación «VEHICLE_TYPES»
  Where: función PL/pgSQL create_workshop(integer,integer) en la línea 17 en sentencia SQL] [HikariProxyCallableStatement@1033639122 wrapping call create_workshop(1,503)]; SQL [HikariProxyCallableStatement@1033639122 wrapping call create_workshop(1,503)]
2023-12-28T06:01:13.783-06:00 ERROR 19464 --- [nio-8080-exec-8] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.springframework.transaction.UnexpectedRollbackException: Transaction silently rolled back because it has been marked as rollback-only] with root cause

org.springframework.transaction.UnexpectedRollbackException: Transaction silently rolled back because it has been marked as rollback-only